apiVersion: v1
kind: Secret
metadata:
  name: flag-secrets
  namespace: flag
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9mbGFnc2VydmljZTpiYW5kZWlyYTEyMzRAcG9zdGdyZXMtZmxhZy5jNzJrNDJlNnl5c24udXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvcG9zdGdyZXM=
  AUTH_SERVICE_URL: aHR0cDovL2F1dGgtc2VydmljZS5hdXRoLnN2Yy5jbHVzdGVyLmxvY2FsOjgw
