apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9hdXRoOnBvc3RncmVzLWF1dGhAcG9zdGdyZXMtYXV0aC5jNzJrNDJlNnl5c24udXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tL3Bvc3RncmVzP3NzbG1vZGU9cmVxdWlyZQ==
  POSTGRES_USER: YXV0aA==
  POSTGRES_PASSWORD: cG9zdGdyZXMtYXV0aA==
  MASTER_KEY: YWRtaW4tc2VjcmV0by0xMjM=