apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: analytics
type: Opaque
data:
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vNjM3NDIzMjYyMDM5L1RlY2hDaGFsbGVuZ2U=
  AWS_REGION: dXMtZWFzdC0x
  DYNAMODB_ENDPOINT: aHR0cDovL2R5bmFtb2RiOjgwMDA=
  AWS_DYNAMODB_TABLE: VG9nZ2xlTWFzdGVyQW5hbHl0aWNz
