apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: analytics
type: Opaque
data:
  AWS_SQS_URL: BASE64_SQS_URL
  AWS_REGION: BASE64_REGION
  DYNAMODB_TABLE: BASE64_TABLE_NAME
