apiVersion: v1
kind: Secret
metadata:
  name: targeting-secrets
  namespace: targeting
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly90YXJnZXRpbmc6dGFyZ2V0aW5nMTIzNEBwb3N0Z3Jlc3MtdGFyZ2V0aW5nLmM3Mms0MmU2eXlzbi51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi9wb3N0Z3Jlcw==
  AUTH_SERVICE_URL: aHR0cDovL2F1dGgtc2VydmljZS5hdXRoLnN2Yy5jbHVzdGVyLmxvY2FsOjgw
