apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secrets
  namespace: evaluation
type: Opaque
data:
  REDIS_URL: BASE64_REDIS_URL
  AWS_SQS_URL: BASE64_SQS_URL
  AWS_REGION: BASE64_REGION
  SERVICE_API_KEY: BASE64_API_KEY
