apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secrets
  namespace: evaluation
type: Opaque
data:
    REDIS_URL: cmVkaXNzOi8vdGFyZ2V0aW5nLXNlcnZpY2UtcmVkaXMtaWdnaWRzLnNlcnZlcmxlc3MudXNlMS5jYWNoZS5hbWF6b25hd3MuY29tOjYzNzk=
    FLAG_SERVICE_URL: aHR0cDovL2ZsYWctc2VydmljZS5mbGFnLnN2Yy5jbHVzdGVyLmxvY2Fs
    TARGETING_SERVICE_URL: aHR0cDovL3RhcmdldGluZy1zZXJ2aWNlLnRhcmdldGluZy5zdmMuY2x1c3Rlci5sb2NhbA==
    AUTH_SERVICE_URL: aHR0cDovL2F1dGgtc2VydmljZS5hdXRoLnN2Yy5jbHVzdGVyLmxvY2FsOjgw
    SERVICE_API_KEY: dG1fa2V5XzA4NjFhZjE2ZDUwMWM1NmE0MWE5NTBkNWNlM2NkMzg2MGJlMGI4MjM2OTE0MGNmYzI1OWIxNzc3ODc2MTM1YjI=
    AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vNjM3NDIzMjYyMDM5L1RlY2hDaGFsbGVuZ2U=
    AWS_REGION: dXMtZWFzdC0x